// Java Package flashlight is a proxy for talking to a Go program.
//   gobind -lang=java github.com/getlantern/lantern-android/libflashlight/bindings
//
// File is generated by gobind. Do not edit.
package go.flashlight;

import go.Seq;

public abstract class Flashlight {
    private Flashlight() {} // uninstantiable
    
    public static String GetFireTweetVersion() {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        String _result;
        Seq.send(DESCRIPTOR, CALL_GetFireTweetVersion, _in, _out);
        _result = _out.readString();
        return _result;
    }
    
    public static void RunClientProxy(String listenAddr, String appName) throws Exception {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        _in.writeString(listenAddr);
        _in.writeString(appName);
        Seq.send(DESCRIPTOR, CALL_RunClientProxy, _in, _out);
        String _err = _out.readString();
        if (_err != null) {
            throw new Exception(_err);
        }
    }
    
    public static void StopClientProxy() throws Exception {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        Seq.send(DESCRIPTOR, CALL_StopClientProxy, _in, _out);
        String _err = _out.readString();
        if (_err != null) {
            throw new Exception(_err);
        }
    }
    
    private static final int CALL_GetFireTweetVersion = 1;
    private static final int CALL_RunClientProxy = 2;
    private static final int CALL_StopClientProxy = 3;
    private static final String DESCRIPTOR = "flashlight";
}
